spring:
  data:
    mongodb:
      #username: root
      #password: root
      database: asset
      port: 27017
      host: localhost
  cloud:
    stream:
      bindings:
        input:
          destination: amq.topic
          binder: rabbit
          group: sensor-consumer-group
        output:
          destination: iot.edge.topic
          binder: rabbit
      rabbit:
        bindings:
          input:
            consumer:
              queueNameGroupOnly: true
              bindingRoutingKey: ".sensor"
  rabbitmq:
    host: localhost
    password: admin
    username: admin