spring:
  data:
    mongodb:
      #username: root
      #password: root
      database: asset
      port: 27017
      host: localhost

server:
  port: 9091
---
spring:
  profiles: docker-compose
  data:
    mongodb:
      #username: root
      #password: root
      database: asset
      port: 27017
      host: mongodb