spring:
  data:
    mongodb:
      #username: root
      #password: root
      database: asset
      port: 27017
      host: localhost
---
spring:
  profiles: docker-compose
  data:
    mongodb:
      #username: root
      #password: root
      database: asset
      port: 27017
      host: mongodb